### ISSUE TITLE
Font color

### ISSUE THREAD

**Issue by BrickZ28** [realrashid/sweet-alert#152]
- Package Version: #.#.#
- Laravel Version: #.#.#

### Description:

How can I, or what drives the color of the text of the alert message. Sweet alert was working fine and it seems after i changed the CSS files of one of my HTML themes the message color now displays as white and i can only see the message if i highlight .  Thanks for any help

### Steps To Reproduce:

**Comment by realrashid** [comment]
@BrickZ28 ,

Please checkout the environment variables from docs.

There you will find the 

```css


customClass: {
  container: '...',
  popup: '...',
  header: '...',
  title: '...',
  closeButton: '...',
  icon: '...',
  image: '...',
  htmlContainer: '...',
  input: '...',
  inputLabel: '...',
  validationMessage: '...',
  actions: '...',
  confirmButton: '...',
  denyButton: '...',
  cancelButton: '...',
  loader: '...',
  footer: '....',
  timerProgressBar: '....',
}

```
